gha-runner-scale-set:
  githubConfigUrl: "https://github.com/anomaly51"
  githubConfigSecret: "github-auth-secret"
  runnerScaleSetName: "argocd-runners"
  minRunners: 0
  maxRunners: 5
  controllerServiceAccount:
    namespace: github-actions-agent
    name: github-actions-agent-gha-rs-controller
  containerMode:
    type: "dind"
  template:
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
        - name: dind
          image: docker:dind
          args:
            - dockerd
            - --host=unix:///run/docker/docker.sock
            - --group=$(DOCKER_GROUP_GID)
            - --insecure-registry=192.168.1.154

