gha-runner-scale-set:
  githubConfigUrl: "https://github.com/anomaly51"
  githubConfigSecret: "github-auth-secret"
  runnerScaleSetName: "argocd-runners"
  minRunners: 0
  maxRunners: 5
  controllerServiceAccount:
    namespace: github-actions-agent
    name: github-actions-agent-gha-rs-controller

