apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: utility-database
spec:
  teamId: "utility"
  volume:
    size: 5Gi
    storageClass: nfs-client
  numberOfInstances: 1
  users:
    utility_admin:
      - superuser
      - createdb
  databases:
    utility_db: utility_admin
  postgresql:
    version: "15"

