apiVersion: v1
kind: Secret
metadata:
  name: utility_admin.utility-database.credentials.postgresql.acid.zalan.do
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  username: utility_admin
  password: "123123"

