apiVersion: v1
kind: Secret
metadata:
  name: utilityadmin.utility-database.credentials.postgresql.acid.zalan.do
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  username: utilityadmin
  password: "123123"

