postgres-operator:
  fullnameOverride: "postgres-operator"
  configKubernetes:
    enable_cross_namespace_secret: true

postgres-operator-ui:
  fullnameOverride: "postgres-operator-ui"
  envs:
    operatorApiUrl: "http://postgres-operator:8080"

