forgejo:
  global:
    storageClass: "nfs-client"

  gitea:
    admin:
      username: "forgejoadmin"
      password: "ForgejoPassword123!"

  service:
    http:
      type: LoadBalancer
    ssh:
      type: LoadBalancer

  ingress:
    enabled: false

