forgejo:
  global:
    storageClass: "nfs-client"

  gitea:
    admin:
      username: "forgejoadmin"
      password: "ForgejoPassword123!"

  service:
    http:
      type: ClusterIP
    ssh:
      type: ClusterIP

  ingress:
    enabled: false
