apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: my-db
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  teamId: "admin"
  volume:
    size: 5Gi
    storageClass: local-path
  numberOfInstances: 1
  users:
    admin:
      - superuser
      - createdb
  databases:
    maindb: admin
  postgresql:
    version: "16"

