apiVersion: v1
kind: Secret
metadata:
  name: admin.my-db.credentials.postgresql.acid.zalan.do
  annotations:
    argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
  username: admin
  password: admin
