apiVersion: v1
kind: Secret
metadata:
  name: postgres.db.credentials.postgresql.acid.zalan.do
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  username: postgres
  password: postgss
