apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-workflow-sa
  namespace: argo-workflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-executor
  namespace: argo-workflows
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-executor-binding
  namespace: argo-workflows
subjects:
  - kind: ServiceAccount
    name: gitops-workflow-sa
    namespace: argo-workflows
roleRef:
  kind: Role
  name: workflow-executor
  apiGroup: rbac.authorization.k8s.io

