---
apiVersion: v1
kind: Secret
metadata:
  name: pulp-external-db
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Создаем до того, как поднимется сам Pulp
type: Opaque
stringData:
  # Используем внутренний DNS кластера для подключения к БД Zalando
  POSTGRES_HOST: utility-database.utility-database.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_USERNAME: utility_admin
  # СЮДА ВПИШИ ПАРОЛЬ ОТ utility_admin, который ты получал ранее.
  # Так как это GitOps, секрет хранится в Git (в будущем рекомендую внедрить SOPS/SealedSecrets)
  POSTGRES_PASSWORD: u3QBUAhcdYcv0dHe46OrukcFbBrVex3y1JcxpyXRsuB7ihTuaWNUKBdBbgktLbPg
  POSTGRES_DB_NAME: utility_db
  POSTGRES_SSLMODE: require

---
apiVersion: v1
kind: Secret
metadata:
  name: pulp-admin-password
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  # Задай свой пароль для УИ и Docker login
  password: "12345"
