---
apiVersion: v1
kind: Secret
metadata:
  name: pulp-external-db
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  POSTGRES_HOST: utility-database.utility-database.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_USER: utilityadmin
  POSTGRES_PASSWORD: "123123"
  POSTGRES_DB: utility_db
  POSTGRES_SSLMODE: require
---
apiVersion: v1
kind: Secret
metadata:
  name: pulp-admin-password
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  password: "12345"

